name: terraform-apply

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  setup:
    timeout-minutes: 30
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.list-targets.outputs.targets }}
    steps:
      - uses: actions/checkout@v4

      - uses: aquaproj/aqua-installer@v3.0.1
        with:
          aqua_version: v2.42.2

      # TODO: 公式のactionに変える（https://github.com/actions/create-github-app-token）
      - id: github_app_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - uses: suzuki-shunsuke/tfaction/list-targets@v1.13.1
        id: list-targets
        with:
          github_token: ${{ steps.github_app_token.outputs.token }}

  apply:
    # setup で取得した変更のある作業ディレクトリが空の場合は実行しない
    if: join(fromJSON(needs.setup.outputs.targets), '') != ''
    name: apply (${{matrix.target.target}})
    runs-on: ubuntu-latest
    needs: setup
    permissions:
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJSON(needs.setup.outputs.targets) }}
    env:
      TFACTION_IS_APPLY: "true"
      TFACTION_WORKING_DIR: ${{ matrix.target.target }}
      TFACTION_JOB_TYPE: terraform
    steps:
      - uses: actions/checkout@v4
      - uses: aquaproj/aqua-installer@v3.0.1
        with:
          aqua_version: v2.42.2

      - id: github_app_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - uses: suzuki-shunsuke/tfaction/setup@v1.13.1
        with:
          github_app_token: ${{ steps.github_app_token.outputs.token }}

      - uses: suzuki-shunsuke/tfaction/apply@v1.13.1
        with:
          github_app_token: ${{ steps.github_app_token.outputs.token }}

      - name: Generate token for creating follow up pr
        id: follow_up_pr_token
        if: failure()
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          # contents:write - Push commits
          # pull_requests:write - Create a pull request
          permissions: >-
            {
              "contents": "write",
              "pull_requests": "write"
            }
          repositories: >-
            [
              "${{github.event.repository.name}}"
            ]

      - uses: suzuki-shunsuke/tfaction/create-follow-up-pr@v1.13.1
        if: failure()
        with:
          github_token: ${{steps.follow_up_pr_token.outputs.token}}
